// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlCvmn3ntMFgxKwdw8l_QQSAI94rq-sE0',
    appId: '1:759117006163:web:ea8174a199f6320679cda6',
    messagingSenderId: '759117006163',
    projectId: 'alhoda-e844b',
    authDomain: 'alhoda-e844b.firebaseapp.com',
    databaseURL: 'https://alhoda-e844b-default-rtdb.firebaseio.com',
    storageBucket: 'alhoda-e844b.appspot.com',
    measurementId: 'G-DD6Q1VX1JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpk86k43axmhDkr8j43hgOT8JQyvDAwOs',
    appId: '1:759117006163:android:06b945030bec926579cda6',
    messagingSenderId: '759117006163',
    projectId: 'alhoda-e844b',
    databaseURL: 'https://alhoda-e844b-default-rtdb.firebaseio.com',
    storageBucket: 'alhoda-e844b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36RQZy-qJd5LnVyaFYWE-2qnH7glCWVQ',
    appId: '1:759117006163:ios:a881092ad2825c7779cda6',
    messagingSenderId: '759117006163',
    projectId: 'alhoda-e844b',
    databaseURL: 'https://alhoda-e844b-default-rtdb.firebaseio.com',
    storageBucket: 'alhoda-e844b.appspot.com',
    iosClientId: '759117006163-k2kncjl1etmdqjmlmf83tuft1s2tar18.apps.googleusercontent.com',
    iosBundleId: 'com.glory-apps.alhoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB36RQZy-qJd5LnVyaFYWE-2qnH7glCWVQ',
    appId: '1:759117006163:ios:a881092ad2825c7779cda6',
    messagingSenderId: '759117006163',
    projectId: 'alhoda-e844b',
    databaseURL: 'https://alhoda-e844b-default-rtdb.firebaseio.com',
    storageBucket: 'alhoda-e844b.appspot.com',
    iosClientId: '759117006163-k2kncjl1etmdqjmlmf83tuft1s2tar18.apps.googleusercontent.com',
    iosBundleId: 'com.glory-apps.alhoda',
  );
}
